name: FossilNOW
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11.1
  - conda-forge::scikit-surprise
  - dash
  - pandas
  - geopandas
  - plotly
  - scikit-learn
  - scipy
  - numpy
  - pytorch::pytorch
  - pip
  - pip:
    - dash-daq
    - dash-mantine-components==0.12.1
  